version: "3.8"

services:
  nginx-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-manager
    restart: unless-stopped
    ports:
      - "80:80"      # HTTP
      - "443:443"    # HTTPS
      - "50001:81"   # NPM web UI
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt

  app:
    build: ./nodejs
    container_name: wildwest-nodejs
    restart: unless-stopped
    ports:
      - "3000:3000"  # for direct access / debugging
    environment:
      - PORT=3000
    # no volumes -> use what's baked into the image
